routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/my/requests');
})->middleware('auth');

Auth::routes();
Route::get('/my/requests', 'RequestController@indexUserRequests');
Route::get('/assigned/requests', 'RequestController@indexAssignedRequests');
Route::resources([
    'user' => 'UserController',
    'request' => 'RequestController'
]);
Route::get('/deny/request/{id}','RequestController@showDenyRequest');
Route::post('/deny/request/{id}','RequestController@denyRequest');
#ESTA NO SE DE DONDE SALIO -->Route::get('/misionoficial', 'RequestController@showMisionForm');
Route::get('/viaticos/create', 'RequestController@showViaticoForm');
Route::get('/cert-horarios/create','RequestController@showHorarioForm');
Route::get('/cert-sueldos-devengados/create', 'RequestController@showSueldosForm');
Route::get('/cert-trabajo/create','RequestController@showTrabajoForm');
Route::get('/pago-serv-pro/create','RequestController@showServProfForm');
Route::get('/devol-desc-mas/create','RequestController@showDevolucionForm');

Route::get('/dashboard','DashboardController@show');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name', 'last_name', 'cedula', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $table = 'users';

    public function getFullNameAttribute()
    {
	    return "{$this->first_name} {$this->last_name}";
    }

    public function roles()
    {
        return $this->belongsToMany('App\UserRole', 'users_user_roles', 'user_id', 'user_role_id');
    }

    public function requestsBy()
    {
        return $this->hasMany('App\FormRequest', 'requester_id', 'id');
    }

    public function requestsTo()
    {
        return $this->hasMany('App\FormRequest', 'incharge_id', 'id');
    }
}

resources/views/forms_show/certificacionHorario.blade.php
@extends('layouts.app')
@section('content')
	<div class="container">
		<div>
			<h2>Detalles de Solicitud de Certificaciones de Horarios</h2>
			<p class="lead">
				En la Certificación de horario de labores se detalla el horario y periodo en que laboró un docente. Una de las razones por las cuales los docentes solicitan esta certificación es para cumplir con uno de los requisitos del proceso de jubilación.<br />
				<small class="text-muted">Consulta sobre certificaciones de horarios en: <a href="http://www.utp.ac.pa/certificaciones" target="blank">Universidad Tecnológica de Panamá - Viáticos</a></small>
			</p>

			<hr />

			<div class="row">
					<div class="form-row">
						<div class="col-sm-4 form-group float-label-control">
							<label><strong>Nombre:</strong></label><p> {{ $body->nombre }}</p>
						</div>
						<div class="col-sm-4 form-group float-label-control">
							<label><strong>Cédula:</strong></label><p> {{ $body->cedula }}</p>
						</div>
						<div class="col-sm-4 form-group float-label-control">
							<label for=""><strong>Detalles sobre el periodo de labor</strong></label> <p>{{$body->detallesHorarioPeriodo}}</p>
						</div>
					</div>


			</div>

			<hr />
			<div class="d-flex justify-content-center">
				@if ($requestStatus == 1)
					<div class="form-group float-label-control">
						@if (Auth::id() == $formRequest->requester_id)
							<h3>Su solicitud ha sido enviada y esta siendo evaluada</h3>
						@elseif (Auth::id() == $formRequest->incharge_id)
				<form class="container-fluid"role="form" method="POST" action="/request/{{ $formRequest->id }}">
					@method('PUT')
					@csrf
							<div class="form-group float-label-control">
								<button class="btn btn-primary" type="submit" name="requestStatusId" value="2">Procesar</button>
				<a class="btn btn-danger" href="/deny/request/{{$formRequest->id}}" >Rechazar</a>
							</div>
				</form>
						@endif
					</div>
				@elseif ($requestStatus == 2)
					<div class="form-group float-label-control">
						@if (Auth::id() == $formRequest->requester_id)
							<h3>Su solicitud fue aceptada y se esta procesando. Por favor esperar hasta que la persona responsable le de una respuesta.</h3>
						@elseif (Auth::id() == $formRequest->incharge_id)
							<h3>Insertar la información necesaria para responder a la solicitud</h3>
							<form class="container-fluid" enctype= "multipart/form-data" role="form" method="POST" action="/request/{{ $formRequest->id }}">
								@method('PUT')
								@csrf
								<div class="form-group">
									<label>Certificado / Documento Validador:</label>
									<input type="file" name="documento" id="" class="form-control">
								</div>
								<div class="form-group">
									<label>Instrucciones u observaciones adicionales:</label>
									<textarea class="form-control" name="obs" placeholder="Participación en el foro: UTP EMPRENDE en el hotel Hilton." rows="5"></textarea>
								</div>
								<input type="hidden" name="action" value="respond">
								<button class="btn btn-primary" type="submit" name="requestStatusId" value="4">Enviar</button>
							</form>
						@endif
					</div>
				@elseif ($requestStatus == 3)
					<div class="form-group float-label-control">
						<div class="alert alert-danger">
							<h3>Solicitud Rechazada</h4>
							<p><strong>Razon: </strong>{{$formRequest->response()->first()->obs}} </p>
						</div>
					</div>
				@elseif ($requestStatus == 4)
					<div class="form-group float-label-control">
						@if (Auth::id() == $formRequest->requester_id)
							<h3>Su solicitud fue aceptada. Esta es la respuesta de la persona responsable de su solicitud.</h3><br>
						@elseif (Auth::id() == $formRequest->incharge_id)
							<h3>Respuesta enviada:</h3><br>
						@endif
							<h4>Instrucciones u observaciones adicionales:</h4>
							<p>{{$formRequest->response()->first()->obs}} </p>
							<a href="/storage/{{$formRequest->response()->first()->documento}}" class="btn btn-primary">Descargar Certificado</a>
					</div>
				@endif
			</div>



		</div>
	</div>
	</div>
@endsection

resources/views/forms_show/certificacionTrabajo.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div>
			<h2>Detalles de Solicitud de Certificaciones de Trabajo</h2>
			<p class="lead">Este procedimiento es relativo a la muestra del historial laboral de los funcionarios.</p>


        <div class="row">
					<div class="col-sm form-group ">
						<label><strong>Nombre:</strong></label><p> {{ $body->name }}</p>
					</div>
					<div class="col-sm form-group ">
						<label><strong>Cédula:</strong></label><p> {{ $body->cedula }}</p>
					</div>

	</div>
			<hr />
		            <div class="d-flex justify-content-center">
                            @if ($requestStatus == 1)
                                <div class="form-group float-label-control">
                                    @if (Auth::id() == $formRequest->requester_id)
                                    <h3>Su solicitud ha sido enviada y esta siendo evaluada</h3>
                                    @elseif (Auth::id() == $formRequest->incharge_id)
					    <form class="container-fluid"role="form" method="POST" action="/request/{{ $formRequest->id }}">
						    @method('PUT')
						    @csrf
						    <div class="form-group float-label-control">
							    <button class="btn btn-primary" type="submit" name="requestStatusId" value="2">Procesar</button>
				<a class="btn btn-danger" href="/deny/request/{{$formRequest->id}}" >Rechazar</a>
						    </div>
					    </form>
                                    @endif
				@elseif ($requestStatus == 2)
					<div class="form-group float-label-control">
						@if (Auth::id() == $formRequest->requester_id)
							<h3>Su solicitud fue aceptada y se esta procesando. Por favor esperar hasta que la persona responsable le de una respuesta.</h3>
						@elseif (Auth::id() == $formRequest->incharge_id)
							<h3>Insertar la información necesaria para responder a la solicitud</h3>
							<form class="container-fluid" enctype= "multipart/form-data" role="form" method="POST" action="/request/{{ $formRequest->id }}">
								@method('PUT')
								@csrf
								<div class="form-group">
									<label>Certificado / Documento Validador:</label>
									<input type="file" name="documento" id="" class="form-control">
								</div>
								<div class="form-group">
									<label>Instrucciones u observaciones adicionales:</label>
									<textarea class="form-control" name="obs" placeholder="Participación en el foro: UTP EMPRENDE en el hotel Hilton." rows="5"></textarea>
								</div>
								<input type="hidden" name="action" value="respond">
								<button class="btn btn-primary" type="submit" name="requestStatusId" value="4">Enviar</button>
							</form>
						@endif
					</div>
				@elseif ($requestStatus == 3)
					<div class="form-group float-label-control">
						<div class="alert alert-danger">
							<h3>Solicitud Rechazada</h4>
							<p><strong>Razon: </strong>{{$formRequest->response()->first()->obs}} </p>
						</div>
					</div>
				@elseif ($requestStatus == 4)
					<div class="form-group float-label-control">
						@if (Auth::id() == $formRequest->requester_id)
							<h3>Su solicitud fue aceptada. Esta es la respuesta de la persona responsable de su solicitud.</h3><br>
						@elseif (Auth::id() == $formRequest->incharge_id)
							<h3>Respuesta enviada:</h3><br>
						@endif
							<h4>Instrucciones u observaciones adicionales:</h4>
							<p>{{$formRequest->response()->first()->obs}} </p>
							<a href="/storage/{{$formRequest->response()->first()->documento}}" class="btn btn-primary">Descargar Certificado</a>
					</div>
				@endif
			</div>



		</div>
	</div>
	</div>
@endsection

resources/views/forms_show/devolucion.blade.php
@extends('layouts.app')
@section('content')
	<div class="container">
		<div>
			<h2>Detalles de Devolución por Descuentos demás</h2>
			<p class="lead">
				Certificación de servicio realizado y de recibido conforme<br />
				<small class="text-muted">Consulta sobre las devoluciones por descuentos en: <a href="http://www.utp.ac.pa/viaticos" target="blank">Universidad Tecnológica de Panamá - Devoluciones por Descuentos</a></small>
			</p>

			<hr />
			<div class="row">
					<!--Discutir si lo demas se debe agregar ya que son puros sellos-->
					<div class="form-row">
						<div class="col-sm-4 form-group float-label-control">
							<label><strong>Nombre:</strong></label><p> {{ $body->nombre }}</p>
						</div>
						<div class="col-sm-4 form-group float-label-control">
							<label><strong>Cédula:</strong></label><p> {{ $body->{'cedula/ruc'} }}</p>
						</div>
						<div class="col-sm-4 form-group float-label-control">
							<label><strong>Código Proovedor:</strong></label><p> {{ $body->codigoProveedor }}</p>
						</div>
						<div class="col-sm-4 form-group float-label-control">
							<label><strong>Fecha Elaboración:</strong></label><p> {{ $body->fechaElaboración }}</p>
						</div>
					</div>

					<div class="form-row">
						<div class="col-sm-4 form-group float-label-control">
							<label><strong>Cédula:</strong></label><p> {{ $body->cedulaRepresentante}}</p>
						</div>
						<div class="col-sm-4 form-group float-label-control">
							<label><strong>Teléfono:</strong></label><p> {{ $body->telefonoRepresentante }}</p>
						</div>
						<div class="col-sm-4 form-group float-label-control">
							<label><strong>Endoso:</strong></label><p> {{ $body->endosoNombre}}</p>
						</div>
						<div class="col-sm-4 form-group float-label-control">
							<label><strong>Fecha Endoso:</strong></label><p> {{ $body->endosoFecha }}</p>
						</div>
					</div>

					<div class="form-row">
						<div class="col-sm-4 form-group float-label-control">
							<label><strong>Contrato numero:</strong></label><p> {{ $body->numeroContrato }}</p>
						</div>
						<div class="col-sm-4 form-group float-label-control">
							<label><strong>Adenda:</strong></label><p> {{ $body->numeroAdenda }}</p>
						</div>
						<div class="col-sm-4 form-group float-label-control">
							<label><strong>Convenio:</strong></label><p> {{ $body->numeroConvenio }}</p>
						</div>
						<div class="col-sm-4 form-group float-label-control">
							<label><strong>Resolucion:</strong></label><p> {{ $body->numeroResolucion }}</p>
						</div>
					</div>


					<div class="d-flex justify-content-center">
						@if ($requestStatus == 1)
							<div class="form-group float-label-control">
								@if (Auth::id() == $formRequest->requester_id)
									<h3>Su solicitud ha sido enviada y esta siendo evaluada</h3>
								@elseif (Auth::id() == $formRequest->incharge_id)
								<form class="container-fluid" role="form" method="POST" action="/request/{{ $formRequest->id }}" >
									@method('PUT')
									@csrf
									<div class="form-group float-label-control">
										<button class="btn btn-primary" type="submit" name="requestStatusId" value="2">Procesar</button>
										<a class="btn btn-danger" href="/deny/request/{{$formRequest->id}}">Rechazar</a>
									</div>
								</form>
								@endif
							</div>
						@elseif ($requestStatus == 2)
							<div class="form-group float-label-control">
								@if (Auth::id() == $formRequest->requester_id)    
									<h3>Su solicitud fue aceptada y se esta procesando. Por favor esperar hasta que la persona responsable le de una respuesta.</h3>
								@elseif (Auth::id() == $formRequest->incharge_id)
								<form class="container-fluid" enctype= "multipart/form-data" role="form" method="POST" action="/request/{{ $formRequest->id }}">
										@method('PUT')
										@csrf
									<h3>Insertar la información necesaria para la persona solicitante:</h3>
									<h4>Certificado / Documento Validador:</h4>
									<input type="file" name="documento" id="" class="form-control">
									<h4>Instrucciones u observaciones adicionales:</h4>
									<textarea class="form-control" name="obs" placeholder="Participación en el foro: UTP EMPRENDE en el hotel Hilton."
											 rows="5"></textarea>
									<input type="hidden" name="action" value="respond">
									<button class="btn btn-primary" type="submit" name="requestStatusId" value="4">Enviar</button>
								</form>
								@endif
							</div>
						@elseif ($requestStatus == 3)
							<div class="form-group float-label-control">
						<div class="alert alert-danger">
							<h3>Solicitud Rechazada</h4>
							<p><strong>Razon: </strong>{{$formRequest->response()->first()->obs}} </p>
						</div>
							</div>
						@elseif ($requestStatus == 4)
						<div class="form-group float-label-control">
							@if (Auth::id() == $formRequest->requester_id)
								<h3>Su solicitud fue aceptada. Esta es la respuesta de la persona responsable de su solicitud.</h3><br>
							@elseif (Auth::id() == $formRequest->incharge_id)
								<h3>Respuesta enviada:</h3><br>
							@endif
							<h4>Instrucciones u observaciones adicionales:</h4>
							<p>{{$formRequest->response()->first()->obs}} </p>
							<a href="/storage/{{$formRequest->response()->first()->documento}}" class="btn btn-primary">Descargar Certificado</a>
						</div>
						@endif
					</div>


			</div>
		</div>
	</div>
@endsection

resources/views/forms_show/pago_por_servicio.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div>
        <h2>Detalles de Solicitud de Pagos por Servicio Profesional</h2>
        <p class="lead">
            Certificación de servicio realizado y de recibido conforme<br />
            <small class="text-muted">Consulta sobre los servicios profesionales en: <a href="http://www.utp.ac.pa/viaticos" target="blank">Universidad Tecnológica de Panamá - Servicios Profesionales</a></small>
        </p>

        <hr />

        <div class="row">
		<div class="container-fluid">
                    <div class="form-row">
                        <div class="col-sm-4 form-group float-label-control">
                            <label><strong>Nombre:</strong></label><p> {{ $body->name }}</p>
                        </div>
                        <div class="col-sm-4 form-group float-label-control">
                            <label><strong>Cédula:</strong></label><p> {{ $body->cedula }}</p>
                        </div>
                        <div class="col-sm-4 form-group float-label-control">
                            <label><strong>Cargo que desempeña:</strong></label><p> {{ $body->role }}</p>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-sm-4 form-group float-label-control">
                            <label for=""><strong>Lugar de Residencia:</strong></label> <p>{{ $body->home_address }}</p>
                        </div>
                        <div class="col-sm-4 form-group float-label-control">
                            <label for=""><strong>Observaciones adicionales:</strong></label> <p>{{ $body->add_observations }}</p>
                        </div>
                        <div class="col-sm-4 form-group float-label-control">
                            <label for=""><strong>Servicio:</strong></label> <p>{{ $body->objective }}</p>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-sm-6 form-group float-label-control">
                            <label for=""><strong>Lugar del servicio:</strong></label> <p>{{ $body->place }}</p>
                        </div> 
                        <div class="col-sm-6 form-group float-label-control">
                            <label class="label"><strong>Fecha del servicio:</strong></label> <p>{{ $body->checkInDate }}</p>
                        </div>
                    </div>

                    <div class="form-row">
                            <div class="col-sm-6 form-group float-label-control">
                                    <label for=""><strong>Hora de llegada:</strong></label> <p>{{ $body->checkIntTime }}</p>
                                </div>
                                <div class="col-sm-6 form-group float-label-control">
                                    <label for=""><strong>Hora de salida:</strong></label> <p>{{ $body->checkOutDate }}</p>
                                </div>
                    </div>
                    
                    </div>
                    
	</div>
                    <div class="d-flex justify-content-center">
                        @if ($requestStatus == 1)
                        <div class="form-group float-label-control">
                            @if (Auth::id() == $formRequest->requester_id)
                            <h3>Su solicitud ha sido enviada y esta siendo evaluada</h3>
                            @elseif (Auth::id() == $formRequest->incharge_id)
							<h3>Insertar la información necesaria para responder a la solicitud</h3>
							<form class="container-fluid" enctype= "multipart/form-data" role="form" method="POST" action="/request/{{ $formRequest->id }}">
								@method('PUT')
								@csrf
								<div class="form-group">
									<label>Certificado / Documento Validador:</label>
									<input type="file" name="documento" id="" class="form-control">
								</div>
								<div class="form-group">
									<label>Instrucciones u observaciones adicionales:</label>
									<textarea class="form-control" name="obs" placeholder="Participación en el foro: UTP EMPRENDE en el hotel Hilton." rows="5"></textarea>
								</div>
								<input type="hidden" name="action" value="respond">
								<button class="btn btn-primary" type="submit" name="requestStatusId" value="4">Enviar</button>
							</form>
                            @endif
                        </div>
                        @elseif ($requestStatus == 2)
                        <div class="form-group float-label-control">
                            @if (Auth::id() == $formRequest->requester_id)
                            <h3>Su solicitud fue aceptada y se esta procesando. Por favor esperar hasta que la persona responsable le de una respuesta.</h3>
                            @elseif (Auth::id() == $formRequest->incharge_id)
                            <h3>Insertar la información necesaria para la persona solicitante:</h3>
                            <h4>Certificado / Documento Validador:</h4>
                            <input type="file" name="Certificado/DocumentoValidador" id="" class="form-control">
                            <h4>Instrucciones u observaciones adicionales:</h4>
                            <textarea class="form-control" name="Instrucciones u observaciones adicionales" placeholder="Participación en el foro: UTP EMPRENDE en el hotel Hilton."
                                rows="5"></textarea>
                            <button class="btn btn-primary" type="submit" name="requestStatusId" value="4">Enviar</button> @endif
                        </div>
                        @elseif ($requestStatus == 3)
                        <div class="form-group float-label-control">
						<div class="alert alert-danger">
							<h3>Solicitud Rechazada</h4>
							<p><strong>Razon: </strong>{{$formRequest->response()->first()->obs}} </p>
						</div>
                        </div>
                        @elseif ($requestStatus == 4)
					<div class="form-group float-label-control">
						@if (Auth::id() == $formRequest->requester_id)
							<h3>Su solicitud fue aceptada. Esta es la respuesta de la persona responsable de su solicitud.</h3><br>
						@elseif (Auth::id() == $formRequest->incharge_id)
							<h3>Respuesta enviada:</h3><br>
						@endif
							<h4>Instrucciones u observaciones adicionales:</h4>
							<p>{{$formRequest->response()->first()->obs}} </p>
							<a href="/storage/{{$formRequest->response()->first()->documento}}" class="btn btn-primary">Descargar Certificado</a>
					</div>
                        @endif
                    </div>
                    


    </div>
</div>
@endsection

resources/views/forms_show/sueldosDevengados.blade.php
@extends('layouts.app')
@section('content')
	<div class="container">
		<div>
			<h2>Detalles de Solicitud de Sueldos Devengados</h2>
			<p class="lead">
				Certificación de servicio realizado y de recibido conforme<br />
				<small class="text-muted">Consulta sobre los sueldos devengados en: <a href="http://www.utp.ac.pa/viaticos" target="blank">Universidad Tecnológica de Panamá - Devengados</a></small>
			</p>

			<hr />

			<div class="row">
				<div class="container-fluid">
					<div class="form-row">
						<div class="col-sm-4 form-group float-label-control">
							<label><strong>Nombre:</strong></label><p> {{ $formRequest->requester()->first()->full_name }}</p>
						</div>
						<div class="col-sm-4 form-group float-label-control">
							<label><strong>Cédula:</strong></label><p> {{ $formRequest->requester()->first()->cedula }}</p>
						</div>
					</div>
					<div class="form-row">
						<div class="col-sm-4 form-group float-label-control">
							<label for=""><strong>Fecha Inicio:</strong></label> <p>{{ $body->CheckInDate }}</p>
						</div>
						<div class="col-sm-4 form-group float-label-control">
							<label for=""><strong>Fecha Final:</strong></label> <p>{{ $body->CheckOutDate }}</p>
						</div>
					</div>
				</div> 
				<div class="container-fluid d-flex justify-content-center">
					@if ($requestStatus == 1)
						<div class="form-group float-label-control">
							@if (Auth::id() == $formRequest->requester_id)
								<h3>Su solicitud ha sido enviada y esta siendo evaluada</h3>
							@elseif (Auth::id() == $formRequest->incharge_id)
								<form class="container-fluid" role="form" method="POST" action="/request/{{ $formRequest->id }}" >
									@method('PUT')
									@csrf
									<div class="form-group float-label-control">
										<button class="btn btn-primary" type="submit" name="requestStatusId" value="2">Procesar</button>
										<a class="btn btn-danger" href="/deny/request/{{$formRequest->id}}" >Rechazar</a>

									</div>
								</form>
							@endif
						</div>
					@elseif ($requestStatus == 2)
						<div class="form-group float-label-control">
							@if (Auth::id() == $formRequest->requester_id)    
								<h3>Su solicitud fue aceptada y se esta procesando. Por favor esperar hasta que la persona responsable le de una respuesta.</h3>
							@elseif (Auth::id() == $formRequest->incharge_id)
							<h3>Insertar la información necesaria para responder a la solicitud</h3>
								<form class="container-fluid" enctype= "multipart/form-data" role="form" method="POST" action="/request/{{ $formRequest->id }}">
									@method('PUT')
									@csrf
									<div class="form-group">
										<label>Certificado / Documento Validador:</label>
										<input type="file" name="documento" id="" class="form-control">
									</div>
									<div class="form-group">
										<label>Instrucciones u observaciones adicionales:</label>
										<textarea class="form-control" name="obs" placeholder="Participación en el foro: UTP EMPRENDE en el hotel Hilton." rows="5"></textarea>
									</div>
									<input type="hidden" name="action" value="respond">
									<button class="btn btn-primary" type="submit" name="requestStatusId" value="4">Enviar</button>
								</form>
							@endif
						</div>
					@elseif ($requestStatus == 3)
						<div class="form-group float-label-control">
							<div class="alert alert-danger">
								<h3>Solicitud Rechazada</h4>
								<p><strong>Razon: </strong>{{$formRequest->response()->first()->obs}} </p>
							</div>
						</div>
					@elseif ($requestStatus == 4)
						<div class="form-group float-label-control">
							@if (Auth::id() == $formRequest->requester_id)
								<h3>Su solicitud fue aceptada. Esta es la respuesta de la persona responsable de su solicitud.</h3><br>
							@elseif (Auth::id() == $formRequest->incharge_id)
								<h3>Respuesta enviada:</h3><br>
							@endif
							<h4>Instrucciones u observaciones adicionales:</h4>
							<p>{{$formRequest->response()->first()->obs}} </p>
							<a href="/storage/{{$formRequest->response()->first()->documento}}" class="btn btn-primary">Descargar Certificado</a>
						</div>
					@endif
				</div>




			</div>
		</div>
	</div>
@endsection